import importlib.util
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts/export-docs-reference.py"
spec = importlib.util.spec_from_file_location("export_docs_reference", SCRIPT)
assert spec and spec.loader
export_docs_reference = importlib.util.module_from_spec(spec)
spec.loader.exec_module(export_docs_reference)


def test_export_docs_reference_includes_current_crds(tmp_path: Path) -> None:
    output = tmp_path / "api.md"

    content = export_docs_reference.generate(export_docs_reference.DEFAULT_CRD)
    output.write_text(content)

    crds = [
        document
        for document in yaml.safe_load_all(export_docs_reference.DEFAULT_CRD.read_text())
        if document and document.get("kind") == "CustomResourceDefinition"
    ]

    assert "<!-- generated by scripts/export-docs-reference.py; do not edit by hand -->" in content
    for crd in crds:
        assert f"## {crd['spec']['names']['kind']}" in content


def test_export_docs_reference_renders_nested_spec_fields() -> None:
    content = export_docs_reference.generate(export_docs_reference.DEFAULT_CRD)

    assert "`spec.externalAddress.value`" in content
    assert "`spec.gatewayRef.name`" in content
    assert "### SIPGateway observability" in content
    assert "`spec.observability.sipHeaders.enabled`" in content
    assert "`spec.observability.sdp.enabled`" in content
    assert "`spec.extensions.extra`" in content
    assert "`spec.pjsip.override`" in content
    assert "`spec.rtp.extra`" in content
    assert "### AsteriskPool extensions.conf" in content
    assert "`spec.trunks`" not in content
    assert "`spec.routes`" not in content
